Crud/Crud/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')),
]

Crud/my_app/urls.py
from django.urls import path
from my_app import views

app_name = 'first_app'

urlpatterns = [
   path('', views.index, name='index'),
   path('students/', views.students, name='students'),
   path('student_info/<int:student_id>/', views.student_info, name='student_info'),
   path('student_update/<int:x_id>/', views.student_update, name='student_update'),
   path('student_delete/<int:x_id>/', views.student_delete, name='student_delete'),
]

Crud/my_app/models.py
from django.db import models

# Create your models here.

class student(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.IntegerField()
    email = models.EmailField(max_length=35)
    department = models.CharField(max_length=50)
    roll = models.IntegerField()
    registration = models.IntegerField()
  


    def __str__(self):
        return str(self.pk) +" "+ self.first_name+" "+ self.last_name +" "+self.department

Crud/my_app/forms.py
from django import forms
from . import models



class StudentForm(forms.ModelForm):
    class Meta:
        model = models.student
        fields = "__all__"

Crud/my_app/views.py
from django.shortcuts import render
from my_app import forms
from my_app.models import student
# Create your views here.

def index(request):
    student_list = student.objects.order_by('first_name')
    diction = {'title':'Home','student_list':student_list}
    return render(request, 'first_project/index.html', context=diction)



def students(request):
    form = forms.StudentForm()

    if request.method == 'POST':
        form = forms.StudentForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction = {'title':'Student Form', 'student_form':form}
    return render(request, 'first_project/student_form.html', context=diction)


def student_info(request,student_id):
    student_info = student.objects.get(pk=student_id)
    diction = {'student_info':student_info}
    return render(request,'first_project/student_info.html', context=diction)


def student_update(request,x_id):
    student_info = student.objects.get(pk=x_id)
    form = forms.StudentForm(instance=student_info)

    if request.method == 'POST':
        form = forms.StudentForm( request.POST, instance=student_info )
        
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        
    diction = {'form':form}
    return render(request, 'first_project/student_update.html', context=diction)



def student_delete(request,x_id):
    students = student.objects.get(pk=x_id).delete()
    diction = {'students':students, 'delete_message':'Delete Done'}
    return render(request,'first_project/student_delete.html', context=diction)

Crud/templates/first_project/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{{ title }}</title>
</head>
<body>
    <ul class="nav">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'first_app:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'first_app:students' %}">Student Form</a>
        </li>
      </ul>

    {% block body_block %}

    {% endblock %}
</body>
</html>

Crud/templates/first_project/index.html
{% extends 'first_project/base.html' %}


{% block body_block %}

<h1>Student List</h1>

{% if student_list %}

  <table border='1'>
    <tr>
        <th>Full Name</th>
        <th>Roll No</th>
        <th>Department</th></colgroup>
    </tr>

    {% for x in student_list %}
    
    <tr>
        <td><a href="{% url 'first_app:student_info' student_id=x.id %}">{{ x.first_name }}{{ x.last_name}}</td></a> 

        <td>{{ x.roll }}</td>
        <td>{{ x.department }}</td>

        
    </tr>
    {% endfor %}

 </table>

<br>
 <a href="{% url 'first_app:students' %}" type="button" class="btn btn-primary" >Add Student</a>

   {% else %}

   <h3>No Student</h3>

{% endif %}
{% endblock %}

Crud/templates/first_project/student_delete.html
{% extends 'first_project/base.html' %}

{% block body_block %}

<h1>Student Delete</h1>

<div class="alert alert-danger">{{ delete_message }}</div>
<a href="{% url 'first_app:index' %}" class="btn btn-primary">Return home</a>
{% endblock %}

Crud/templates/first_project/student_form.html
{% extends 'first_project/base.html' %}


{% block body_block %}

<h1>Student Form</h1>

<form action="" method="post">

    {{ student_form.as_p }}

    {% csrf_token %}

    <input type="submit" class="btn btn-primary" name="submit" value="Submit Form">
    <a href="{% url 'first_app:index'%}" type="button" class="btn btn-primary">Return home</a>
</form>

{% endblock %}

Crud/templates/first_project/student_info.html
{% extends 'first_project/base.html'%}

{% block body_block %}


<h1>Student Information</h1>

<h3>Student Id.{{ student_info.id}}</h3>
<h3>Name: {{ student_info.first_name}}{{ student_info.last_name}}</h3>
<h3>Phone No.{{ student_info.Phone }}</h3>
<h3>Email: {{ student_info.email }}</h3>
<h3>Roll Number: {{ student_info.roll }}</h3>
<h3>Registration Number: {{ student_info.registration }}</h3>

<a href="{% url 'first_app:student_update' x_id=student_info.id %}" type="button" class="btn btn-primary">Update</a>
<a href="{% url 'first_app:student_delete' x_id=student_info.id %}" type="button" class="btn btn-primary">Delete</a>
{% endblock %}

Crud/templates/first_project/student_update.html
{% extends 'first_project/base.html' %}

{% block body_block %}

<h1>Student Update</h1>


<form action="" method="post">
    {{ form.as_p }}
    
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" value="Update">

    <a href="{% url 'first_app:index' %}" class="btn btn-primary">Return home</a>
</form>

{% endblock %}